name: 员工持股自动推送
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

# 👇 加上这一段，强制使用 Node.js 24，警告立刻消失
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: 安装依赖
        run: pip install akshare pandas requests
      - name: 运行脚本
        env:
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
        run: python bot.py
